#!/usr/bin/env bash
#
# Launch Firefox with given profile, or with profile manager (if no profile given)
#
# macOS only

set -o errexit -o nounset -o pipefail

openArgs=(
"-a" "Firefox"
"-n"
)

firefoxArgs=()

if (( $# < 1 ))
then
    firefoxArgs=("-ProfileManager" "-no-remote")
else
    firefoxArgs=("-P" "${1}")
fi

open "${openArgs[@]}" --args "${firefoxArgs[@]}"
