#!/usr/bin/env bash

set -o errexit -o nounset -o pipefail


areDesktopIconsHidden() {
    local value
    
    value=$(defaults read com.apple.finder CreateDesktop)

    if [[ "${value}" == "false" ]]
    then
        return 0
    else
        return 1
    fi
}

showDesktopIcons() {
    defaults write com.apple.finder CreateDesktop true
    killall Finder
}

hideDesktopIcons() {
    defaults write com.apple.finder CreateDesktop false
    killall Finder
}

if areDesktopIconsHidden
then
    showDesktopIcons
else
    hideDesktopIcons
fi
